[2022-01-18 11:47:33,692] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_dag_2.dbt_run 2019-10-17T00:00:00+00:00 [queued]>
[2022-01-18 11:47:33,704] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_dag_2.dbt_run 2019-10-17T00:00:00+00:00 [queued]>
[2022-01-18 11:47:33,704] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:47:33,704] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2022-01-18 11:47:33,704] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:47:33,721] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): dbt_run> on 2019-10-17T00:00:00+00:00
[2022-01-18 11:47:33,725] {standard_task_runner.py:52} INFO - Started process 2182 to run task
[2022-01-18 11:47:33,731] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_dag_2', 'dbt_run', '2019-10-17T00:00:00+00:00', '--job-id', '425', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dbt_example.py', '--cfg-path', '/tmp/tmpcvkbm14a', '--error-file', '/tmp/tmp0jyzq9nc']
[2022-01-18 11:47:33,744] {standard_task_runner.py:77} INFO - Job 425: Subtask dbt_run
[2022-01-18 11:47:33,830] {logging_mixin.py:109} INFO - Running <TaskInstance: example_dag_2.dbt_run 2019-10-17T00:00:00+00:00 [running]> on host 761e1446abdc
[2022-01-18 11:47:33,955] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_dag_2
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2019-10-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-10-17T00:00:00+00:00
[2022-01-18 11:47:33,955] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-18 11:47:33,956] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'dbt run --profiles-dir /home/fcoelho/.dbt --project-dir /home/dev/dbt']
[2022-01-18 11:47:33,995] {subprocess.py:74} INFO - Output:
[2022-01-18 11:47:33,997] {subprocess.py:78} INFO - bash: dbt: command not found
[2022-01-18 11:47:33,999] {subprocess.py:82} INFO - Command exited with return code 127
[2022-01-18 11:47:34,020] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-01-18 11:47:34,022] {taskinstance.py:1505} INFO - Marking task as FAILED. dag_id=example_dag_2, task_id=dbt_run, execution_date=20191017T000000, start_date=20220118T114733, end_date=20220118T114734
[2022-01-18 11:47:34,073] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-01-18 11:47:34,124] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
