[2022-01-18 11:47:00,131] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_dag_2.dbt_run 2019-04-02T00:00:00+00:00 [queued]>
[2022-01-18 11:47:00,154] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_dag_2.dbt_run 2019-04-02T00:00:00+00:00 [queued]>
[2022-01-18 11:47:00,155] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:47:00,155] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2022-01-18 11:47:00,155] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:47:00,186] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): dbt_run> on 2019-04-02T00:00:00+00:00
[2022-01-18 11:47:00,211] {standard_task_runner.py:52} INFO - Started process 1575 to run task
[2022-01-18 11:47:00,219] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_dag_2', 'dbt_run', '2019-04-02T00:00:00+00:00', '--job-id', '227', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dbt_example.py', '--cfg-path', '/tmp/tmpv8i4uq4z', '--error-file', '/tmp/tmpz8fgd3tp']
[2022-01-18 11:47:00,221] {standard_task_runner.py:77} INFO - Job 227: Subtask dbt_run
[2022-01-18 11:47:00,369] {logging_mixin.py:109} INFO - Running <TaskInstance: example_dag_2.dbt_run 2019-04-02T00:00:00+00:00 [running]> on host 761e1446abdc
[2022-01-18 11:47:00,544] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_dag_2
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T00:00:00+00:00
[2022-01-18 11:47:00,545] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-18 11:47:00,545] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'dbt run --profiles-dir /home/fcoelho/.dbt --project-dir /home/dev/dbt']
[2022-01-18 11:47:00,603] {subprocess.py:74} INFO - Output:
[2022-01-18 11:47:00,606] {subprocess.py:78} INFO - bash: dbt: command not found
[2022-01-18 11:47:00,606] {subprocess.py:82} INFO - Command exited with return code 127
[2022-01-18 11:47:00,627] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-01-18 11:47:00,629] {taskinstance.py:1505} INFO - Marking task as FAILED. dag_id=example_dag_2, task_id=dbt_run, execution_date=20190402T000000, start_date=20220118T114700, end_date=20220118T114700
[2022-01-18 11:47:00,722] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-01-18 11:47:00,779] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
