[2022-01-18 11:14:32,406] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_dag 2022-01-18T02:00:00+00:00 [queued]>
[2022-01-18 11:14:32,415] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_dag 2022-01-18T02:00:00+00:00 [queued]>
[2022-01-18 11:14:32,415] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:14:32,415] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-01-18 11:14:32,416] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:14:32,443] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): dbt_dag> on 2022-01-18T02:00:00+00:00
[2022-01-18 11:14:32,453] {standard_task_runner.py:52} INFO - Started process 577 to run task
[2022-01-18 11:14:32,469] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_dag', '2022-01-18T02:00:00+00:00', '--job-id', '126', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dbt_example.py', '--cfg-path', '/tmp/tmp0copgb8h', '--error-file', '/tmp/tmp4s0f28v1']
[2022-01-18 11:14:32,501] {standard_task_runner.py:77} INFO - Job 126: Subtask dbt_dag
[2022-01-18 11:14:32,760] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.dbt_dag 2022-01-18T02:00:00+00:00 [running]> on host 761e1446abdc
[2022-01-18 11:14:33,003] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-01-18T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-18T02:00:00+00:00
[2022-01-18 11:14:33,010] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-18 11:14:33,010] {subprocess.py:63} INFO - Running command: ['bash', '-c', "python -c 'from dbt.main import main; main()' run"]
[2022-01-18 11:14:33,089] {subprocess.py:74} INFO - Output:
[2022-01-18 11:14:33,367] {subprocess.py:78} INFO - Traceback (most recent call last):
[2022-01-18 11:14:33,367] {subprocess.py:78} INFO -   File "<string>", line 1, in <module>
[2022-01-18 11:14:33,367] {subprocess.py:78} INFO - ModuleNotFoundError: No module named 'dbt'
[2022-01-18 11:14:33,374] {subprocess.py:82} INFO - Command exited with return code 1
[2022-01-18 11:14:33,412] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-01-18 11:14:33,414] {taskinstance.py:1505} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_dag, execution_date=20220118T020000, start_date=20220118T111432, end_date=20220118T111433
[2022-01-18 11:14:33,482] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-01-18 11:14:33,562] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
