[2022-01-18 11:47:27,694] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_dag_2.dbt_run 2019-09-09T00:00:00+00:00 [queued]>
[2022-01-18 11:47:27,716] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: example_dag_2.dbt_run 2019-09-09T00:00:00+00:00 [queued]>
[2022-01-18 11:47:27,719] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:47:27,719] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2022-01-18 11:47:27,719] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-01-18 11:47:27,743] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): dbt_run> on 2019-09-09T00:00:00+00:00
[2022-01-18 11:47:27,747] {standard_task_runner.py:52} INFO - Started process 2069 to run task
[2022-01-18 11:47:27,764] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_dag_2', 'dbt_run', '2019-09-09T00:00:00+00:00', '--job-id', '387', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dbt_example.py', '--cfg-path', '/tmp/tmpxcf2qggx', '--error-file', '/tmp/tmp02ss3e03']
[2022-01-18 11:47:27,765] {standard_task_runner.py:77} INFO - Job 387: Subtask dbt_run
[2022-01-18 11:47:27,822] {logging_mixin.py:109} INFO - Running <TaskInstance: example_dag_2.dbt_run 2019-09-09T00:00:00+00:00 [running]> on host 761e1446abdc
[2022-01-18 11:47:27,933] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_dag_2
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2019-09-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-09T00:00:00+00:00
[2022-01-18 11:47:27,933] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-18 11:47:27,934] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'dbt run --profiles-dir /home/fcoelho/.dbt --project-dir /home/dev/dbt']
[2022-01-18 11:47:27,969] {subprocess.py:74} INFO - Output:
[2022-01-18 11:47:27,971] {subprocess.py:78} INFO - bash: dbt: command not found
[2022-01-18 11:47:27,972] {subprocess.py:82} INFO - Command exited with return code 127
[2022-01-18 11:47:27,987] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-01-18 11:47:27,989] {taskinstance.py:1505} INFO - Marking task as FAILED. dag_id=example_dag_2, task_id=dbt_run, execution_date=20190909T000000, start_date=20220118T114727, end_date=20220118T114727
[2022-01-18 11:47:28,017] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-01-18 11:47:28,053] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
